enabled: true # should these trades be registered
log: true # should the plugin log
override_vanilla: false # should it override the vanilla trades with the custom ones

# If override_vanilla is true and no custom trade is defined, the plugin will use the vanilla trades either way!
# The following is just an example!

# trades:
#   vanilla_trades: # vanilla trades here
#     - stone_sword: # vanilla item ID, not case sensitive
#         min_amount: 1 # minimum amount to drop
#         max_amount: 3 # maximum amount to drop
#         chance: 50 # chance in %
#     - iron_sword:
#         min_amount: 1
#         max_amount: 3
#         chance: 30
#     - diamond_sword:
#         min_amount: 1
#         max_amount: 3
#         chance: 10
#   oraxen_trades: # oraxen trades here
#     - obsidian_pickaxe: # oraxen item ID
#         min_amount: 1 # minimum amount to drop
#         max_amount: 3 # maximum amount to drop
#         chance: 10 # chance in %
#     - amethyst_hammer:
#         min_amount: 1
#         max_amount: 3
#         chance: 10
#   mmoitems_trades: # mmoitems trades
#     - SWORD: # mmoitems category name
#         item: "TESTSWORD" # mmoitems item ID
#         min_amount: 1
#         max_amount: 1
#         chance: 50 # chance in %
#     - AXE:
#         item: "AXETEST"
#         min_amount: 1
#         max_amount: 1
#         chance: 50